name: rotnet
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - ca-certificates
  - certifi
  - colorama
  - cudatoolkit
  - cudnn
  - cycler
  - decorator
  - entrypoints
  - freeglut
  - freetype
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jasper
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lerc
  - libblas
  - libcblas
  - libclang
  - libdeflate
  - liblapack
  - liblapacke
  - libopencv
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libtiff
  - libwebp
  - libwebp-base
  - libzlib
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nest-asyncio
  - numpy
  - numpy-base
  - olefile
  - opencv
  - openssl
  - pandas
  - parso
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - py-opencv
  - pygments
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pyzmq
  - qt
  - setuptools
  - sqlite
  - tk
  - tornado
  - traitlets
  - ucrt
  - vc
  - vc14_runtime
  - vs2015_runtime
  - wcwidth
  - wheel
  - wincertstore
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
      - absl-py
      - astunparse
      - cached-property
      - cachetools
      - charset-normalizer
      - clang
      - dataclasses
      - flatbuffers
      - gast
      - google-auth
      - google-auth-oauthlib
      - google-pasta
      - grpcio
      - h5py
      - idna
      - importlib-metadata
      - keras
      - keras-preprocessing
      - markdown
      - oauthlib
      - opt-einsum
      - protobuf
      - pyasn1
      - pyasn1-modules
      - requests
      - requests-oauthlib
      - rsa
      - six
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - tensorflow
      - tensorflow-estimator
      - termcolor
      - typing-extensions
      - urllib3
      - werkzeug
      - wrapt
      - zipp
