name: tensorflow_env  # The name of the Conda environment
channels:
  - defaults           # Default channel for Conda packages
  - conda-forge         # Conda-forge channel for additional community-maintained packages
dependencies:
  # Python and core libraries
  - python=3.9         # Python version 3.9, compatible with TensorFlow 2.10
  - tensorflow=2.10.0  # TensorFlow version 2.10, for deep learning
  - keras=2.10.0       # Keras version 2.10, used with TensorFlow
  - numpy              # NumPy for numerical operations
  - pandas             # Pandas for data manipulation
  - matplotlib         # Matplotlib for data visualization
  - scikit-learn       # Scikit-learn for machine learning and data preprocessing
  - opencv             # OpenCV for computer vision tasks

  # GPU dependencies
  - cudatoolkit=11.2   # CUDA Toolkit 11.2, required for GPU acceleration
  - cudnn=8.1          # cuDNN 8.1, required for TensorFlow GPU support
  # Note: Ensure that your GPU is compatible with CUDA 11.2 and cuDNN 8.1.
  # For compatibility details, check: https://www.tensorflow.org/install/source#gpu

  # pip-installed dependencies
  - pip:
      - keras-tuner    # Keras Tuner for hyperparameter optimization
